# Generated by Django 5.1.4 on 2025-02-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodels',
            name='name',
        ),
    ]
