# Generated by Django 5.1.4 on 2025-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_postmodels_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodels',
            name='image',
            field=models.ImageField(default=0, upload_to='static/'),
            preserve_default=False,
        ),
    ]
