# Generated by Django 5.1.4 on 2025-02-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_postmodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
