# Generated by Django 5.1.4 on 2025-02-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
