# Generated by Django 5.1.4 on 2025-02-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
