# Generated by Django 5.1.4 on 2025-02-17 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_messagebox_author_messagebox_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagebox',
            old_name='datetimesend',
            new_name='datetime_sent',
        ),
        migrations.RemoveField(
            model_name='messagebox',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messagebox',
            name='sender',
        ),
        migrations.AddField(
            model_name='messagebox',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
